services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile

  bookify-db:
   image: postgres:latest


volumes:
  postgres_bookifydb:
